#include "CharacterState.h"




void CharacterState::Enter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B43 begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B43 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CharacterState::Tick()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B49 begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B49 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void CharacterState::Exit()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B4B begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B4B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
