#include "DefendState.h"




void DefendState::Enter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B5D begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B5D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void DefendState::Tick()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B5F begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void DefendState::Exit()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B61 begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B61 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
