#include "IdleState.h"




void IdleState::Enter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B3F begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B3F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void IdleState::Tick()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B45 begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B45 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void IdleState::Exit()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B47 begin
{
    
}
// section -64--88-56-1--2dfbbc57:192f30619e0:-8000:0000000000000B47 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
