#include "Armour.h"




String Armour::getName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A23 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A23 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Armour::getDamageMod()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A25 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A25 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Armour::getRecoveryMod()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A27 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A27 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
