#include "Character.h"




void Character::setName(void  String)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000967 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000967 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

String Character::getName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:000000000000097F begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:000000000000097F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Character::Attack(void  Offense, void  Weapon, void  Character)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000981 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000981 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Character::Defend(void  Defense, void  Armour)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000986 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000986 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
