#include "Defense.h"




void Defense::levelUpHealthPoints()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009DB begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009DB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Defense::levelUpRegeneration()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009DD begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009DD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Defense::levelUpRecovery()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009DF begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009DF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Defense::levelUpDefense()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E1 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Defense::heal()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E5 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Defense::getHealthPoints()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E7 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Defense::getRegeneration()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E9 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009E9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Defense::getRecovery()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009EB begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009EB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Defense::getDefense()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009ED begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009ED end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
