#include "Level.h"




void Level::addExp(void  Integer)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009A8 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009A8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Level::levelUp()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009AB begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009AB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Level::getLevel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009AD begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009AD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Level::getExperience()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009AF begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Level::getNextLevel()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009B1 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
