#include "Offense.h"




void Offense::levelUpDamage()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C1 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Offense::levelUpSpeed()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C3 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Offense::levelUpCoolDown()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C5 begin
{
    
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Offense::getDamage()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C7 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Offense::getSpeed()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C9 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009C9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Offense::getCoolDown()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009CB begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:00000000000009CB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
