#include "Weapon.h"




String Weapon::getName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A12 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A12 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Weapon::getDamageMod()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A14 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A14 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Weapon::getSpeedMod()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A16 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A16 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Float Weapon::getCoolDownMod()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A18 begin
{
}
// section -64--88-56-1--47be576a:192f06fd0e6:-8000:0000000000000A18 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
